steps:
  # Reservations
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'asia-east2-docker.pkg.dev/sleepr-430208/reservations/production',
        '-f',
        'apps/reservations/Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'asia-east2-docker.pkg.dev/sleepr-430208/reservations/production',
      ]
  # Auth
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'asia-east2-docker.pkg.dev/sleepr-430208/auth/production',
        '-f',
        'apps/auth/Dockerfile.dev',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-east2-docker.pkg.dev/sleepr-430208/auth/production']
  # Notifications
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'asia-east2-docker.pkg.dev/sleepr-430208/notifications/production',
        '-f',
        'apps/notifications/Dockerfile.dev',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'asia-east2-docker.pkg.dev/sleepr-430208/notifications/production',
      ]
  # Payments
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'asia-east2-docker.pkg.dev/sleepr-430208/payments/production',
        '-f',
        'apps/payments/Dockerfile.dev',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      ['push', 'asia-east2-docker.pkg.dev/sleepr-430208/payments/production']
