services:
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
    image: auth
    # command: npm run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3001'

  mongo:
    image: mongo
