apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payments
  name: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - image: asia-east2-docker.pkg.dev/sleepr-430208/payments/production
          name: payments
          resources:
            limits:
              cpu: '1'
              memory: '512Mi'
            requests:
              cpu: '0.5'
              memory: '256Mi'
