services:
  e2e:
    build:
      context: .
      dockerfile: ./Dockerfile
    # command: 'ping auth -c 10'
    volumes:
      - ./specs:/usr/src/app/specs
    depends_on:
      - reservations
      - auth
      - payments
      - notifications
      - mongo

  reservations:
    build:
      context: ../
      dockerfile: apps/reservations/Dockerfile
      # dockerfile: ../apps/auth/Dockerfile.dev
      target: development
    command: npm run start:dev reservations
    env_file:
      - ../apps/reservations/.env
    ports:
      - '3000:3000'

  auth:
    build:
      context: ../
      dockerfile: apps/auth/Dockerfile
      # dockerfile: ../apps/auth/Dockerfile.dev
      target: development
    command: npm run start:dev auth
    env_file:
      - ../apps/auth/.env
    ports:
      - '3001:3001'

  payments:
    build:
      context: ../
      dockerfile: apps/payments/Dockerfile
      # dockerfile: ../apps/payments/Dockerfile.dev
      target: development
    command: npm run start:dev payments
    env_file:
      - ../apps/payments/.env
    ports:
      - '3003:3003'

  notifications:
    build:
      context: ../
      dockerfile: apps/notifications/Dockerfile
      # dockerfile: ../apps/notifications/Dockerfile.dev
      target: development

    command: npm run start:dev notifications
    env_file:
      - ../apps/notifications/.env
    ports:
      - '3004:3004'

  mongo:
    image: mongo
